global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'django'
    scheme: https
    static_configs:
      - targets: ['transendence:8043']
    tls_config:
      cert_file: /etc/prometheus/certs/client.crt
      key_file: /etc/prometheus/certs/client.key
      insecure_skip_verify: true
# storage:
#   tsdb:
#     path: /prometheus
#     retention.time: 30d
#     retention.size: 1GB

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 'alertmanager:9093'

rule_files:
  - "alert_rules.yml"
  - "sample-rules.yml"
