# Generated by Django 5.0.6 on 2024-06-25 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_profile_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='online_status',
            field=models.BooleanField(default=False),
        ),
    ]
