# Generated by Django 5.0.6 on 2024-07-05 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_profile_online_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='match_history',
            field=models.TextField(blank=True, null=True),
        ),
    ]
